#ifndef CONSTANTS_H
#define CONSTANTS_H

#define ADC_SAMPLE_RATE_HZ 32000

#define DATA_SIZE_SAMPLES   128
#define DECIMATION_FACTOR   4
#define ACQ_SIZE_SAMPLES    (DATA_SIZE_SAMPLES * DECIMATION_FACTOR)
#define MAGNITUDE_BINS      (DATA_SIZE_SAMPLES / 2)
#define DATA_SAMPLE_RATE    (ADC_SAMPLE_RATE_HZ / DECIMATION_FACTOR)
#define DATA_BANDWIDTH      (DATA_SAMPLE_RATE / 2)
#define HZ_PER_BIN          (DATA_BANDWIDTH / MAGNITUDE_BINS)

#endif
